### ISSUE TITLE
Zoomeye output file naming problem

### ISSUE THREAD

**Issue by AintCoolSon** [jm33-m0/massExpConsole#10]
[*] Your query is: app:"WordPress" ver:"4.6"
[*] How many results do you want? (10 IPs on each page) 10000
[*] Crawling fetched pages from ZoomEye...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "zoomeye.py", line 96, in progress
    l_count = sum(1 for line in open(file))
FileNotFoundError: [Errno 2] No such file or directory: './data/zoomeye-app_"wordpress"-ver_"4.6".txt'

Naming seems to be a bit off, hence I'm unable to crawl for results.

**Comment by AintCoolSon** [comment]
Manually renaming the file created, to the name of the file "not found" example": zoomeye-app"wordpress"-ver"4.6".txt  seems to solve the issue.
EDIT:
Guess not. There is no error reported, but the crawler gets stuck at 0 hosts.
"Found 0 hosts"

**Comment by jm33-m0** [comment]
using `'` or `"` in query text may cause issues, as the script tries to name the output file as `zoomeye-query.txt`

**Comment by AintCoolSon** [comment]
I figured. But why do I get 0 results while doing it via browser gets me couple of thousand? 
For example, app:"WebDAV"

**Comment by jm33-m0** [comment]
@AintCoolSon in fact the script tries to write into `zoomeye-app:"WebDAV".txt`, which has never been created, instead, you can find something like `zoomeye-app_WebDAV.txt` being created

which means, even if it's getting results, it can't write to a file that does not exist, plus, the progress is determined by reading the invalid file as well, which is why you are seeing `Found 0 hosts`

**Comment by AintCoolSon** [comment]
Even when I create the file, the scripts tries to write into, it finds 0 hosts and quits

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/massExpConsole/commit/541fd2d60003ea8a9c03ec5762c30266ecc2524b

fixed

**Comment by AintCoolSon** [comment]
File naming issue fixed, however, doing this search for example:app:"WordPress" ver:"4.6"
Gets me 0 results, without even showing the message, 0 hosts found and exiting the zoomeye. 
Could it be search type that is set on public devices instead on web services?

**Comment by jm33-m0** [comment]
yes that's correct, im opening a new issue for this
![screenshot from 2017-06-06 13-40-06](https://cloud.githubusercontent.com/assets/10167884/26815247/c88d007c-4abd-11e7-962d-4c9cf03e6236.png)
![screenshot from 2017-06-06 13-40-29](https://cloud.githubusercontent.com/assets/10167884/26815259/d95ba278-4abd-11e7-8bd0-48ab8d911515.png)
