### ISSUE TITLE
0 hosts on certain searches that show results

### ISSUE THREAD

**Issue by AintCoolSon** [jm33-m0/massExpConsole#12]
So, basically, this is what happens. 
mec > z
[*] Your query is: app:"Microsoft IIS httpd" ver:"6.0" country:rs
[?] Search for public devices (h) or web services (w)? [h/w] w (or h, doesn't matter. should get results either way)
[*] How many results do you want? (10 IPs on each page) 1000
[*] Crawling fetched pages from ZoomEye...
[+] Found 0 hosts

I've tried using other accounts, with email verified, but no change.

**Comment by jm33-m0** [comment]
when searching for web services, i separate `url` field according to a response example given by [ZoomEye's official doc](https://www.zoomeye.org/api/doc#web-search)
as following:
https://github.com/jm33-m0/massExpConsole/blob/master/zoomeye.py#L131

the response might be different when searching for certain queries, thus no `url` field can be found in response json, writing 0 results

but if you want, you can print every response to debug the script

im gonna make it easier for users to see import messages from zoomeye api server in the next commit

**Comment by jm33-m0** [comment]
ps. if you search for public devices in your example, it does return results without any issue

![screenshot from 2017-06-06 19-23-51](https://cloud.githubusercontent.com/assets/10167884/26826990/bce2bf8e-4aed-11e7-9054-c06385dcf7a6.png)
