### ISSUE TITLE
Add functionnality to zoomeye crawler ?

### ISSUE THREAD

**Issue by Vumasi** [jm33-m0/massExpConsole#13]
Hello,

Do you think it would be possible to add a feature to start zoomeye crawl on a given page or a given number IP ? 
For example : Start to 10000 > Go to 100000

A limitation is fixed on zoomeye, so starting on this idea it would obtain a lot of hosts.

Thank's

**Comment by jm33-m0** [comment]
well i dont think its possible, as zoomeye only allows page 1-10k to be accessed, if what you said is true, then zoomeye doesn't need any limitations... you can get a full list of results by crawling multiple times

if you somehow believe its possible, please crawl page 1000+ and post your result here

**Comment by Vumasi** [comment]
Bad idea :
https://www.zoomeye.org/vip#API
