### ISSUE TITLE
Missing a requirement for Kali 2017.2

### ISSUE THREAD

**Issue by grov** [jm33-m0/massExpConsole#16]
Hey, 

I had to install "python3-bs4" using apt in order to use the tool. 
"sudo apt-get install python3-bs4"

Hope it will help
john

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/massExpConsole/blob/master/requirements.txt#L6
it's already in `requirements.txt`, you can install all deps with `pip3 install -r requirements.txt`
