### ISSUE TITLE
Zoomeye/censys doesnt work

### ISSUE THREAD

**Issue by mmk687** [jm33-m0/massExpConsole#22]
i am using kali llinux and there is no results in using zoomeye nether using censys
when i type ./install.py and reach my account and password for zoomeye and type them,
after i type my username and password ,
isearched the zoomeye it gave me 0 results for any kind of sarch,
i opened zoomeye.conf i dont find my credentials in zoomeye.conf
same as cencys,
i made changes manually to zoomeye.conf i typed my username and password like this
user:username
password:pass
and when i searched a query in zoomeye its also gave me 0 results

**Comment by jm33-m0** [comment]
Zoomeye requires phone number verification, and is only available to Chinese users.
I haven't changed the script since zoomeye closed its API, if you were interested, please read zoomeye's updated docs and adapt the script to use your account.
I will test `install.py`, though

**Comment by jm33-m0** [comment]
- please `git pull` before opening any issues
- ive updated `zoomeye.py`
