### ISSUE TITLE
censys not working

### ISSUE THREAD

**Issue by mmk687** [jm33-m0/massExpConsole#23]
i dont know what does `git pull` mean but anyway i am not a python programmer .
same trouble here 
take this zoomeye activated account and try urself
username: stone@sec.dog
password: Ixw3vFVc65Kk
besides the same  problem is with censys

**Comment by jm33-m0** [comment]
- make sure this account is verified by phone number (+86)
- please use meaningful titles
- i tested my zoomeye account multiple times, could not find any issues
- censys issue will be assigned to its author @p4r71cl3

**Comment by jm33-m0** [comment]
> i dont know what does `git pull` mean

take some time learning how git works, specifically, `git pull` means you have to update your local software repo by pulling commits from remote

> same trouble here
take this zoomeye activated account and try urself

sorry, when one account works, all should work, that's why it's pointless testing your account, also, make sure you are using the latest script from this repo

**Comment by mmk687** [comment]
when i use my account should it be saved in zoomeye.conf cause i found the file empty

**Comment by jm33-m0** [comment]
**UPDATE by git pull** before you report an issue

**Comment by mmk687** [comment]
[Screencast_01-03-2018_12^%23^%58 AM.zip](https://github.com/jm33-m0/massExpConsole/files/1599457/Screencast_01-03-2018_12.23.58.AM.zip)
i did 
and reinstall it again

[Screencast_01-02-2018_11^%42^%30 PM.zip](https://github.com/jm33-m0/massExpConsole/files/1599426/Screencast_01-02-2018_11.42.30.PM.zip)
[Screencast_01-02-2018_11^%56^%26 PM.zip](https://github.com/jm33-m0/massExpConsole/files/1599427/Screencast_01-02-2018_11.56.26.PM.zip)

**Comment by mmk687** [comment]
i guess i might dont have one of its dependencies

**Comment by mmk687** [comment]
i did cloned it again and removed the old files but the same problem i found ,
i dont think the error is in ur code as it worked with u

**Comment by mmk687** [comment]
[Screencast_01-03-2018_12^%23^%58 AM.zip](https://github.com/jm33-m0/massExpConsole/files/1599458/Screencast_01-03-2018_12.23.58.AM.zip)
