### ISSUE TITLE
proxy-pool/proxychains cannot be disabled

### ISSUE THREAD

**Issue by dsx12** [jm33-m0/massExpConsole#41]
After updating to latest version and selecting "N"/no for proxychains; I receive the following errors:
[-] proxy_pool not configured, type `set proxy-pool` to configure
[-] Cannot get proxy from proxy_pool

I'd much rather just use my VPN, any way to get around this?

Screenshot:
![image](https://user-images.githubusercontent.com/45248846/83836579-6164bb80-a6e3-11ea-9aa4-681fd452427a.png)

**Comment by jm33-m0** [comment]
This is actually a bug, thanks for reporting

**Comment by dsx12** [comment]
@jm33-m0 let me know when it's fixed, love the tool.

**Comment by jm33-m0** [comment]
It's already been fixed, you can update and try again
