### ISSUE TITLE
Using .lower() creating a bug.

### ISSUE THREAD

**Issue by dsx12** [jm33-m0/massExpConsole#42]
The python builtin .lower() generates a bug:

When setting a value for target if the directory has capital letters in it the .lower()
function will convert the capital letters into lowercase letters ineffectively creating a bug when mec attempts to read the target file (This bug only pertains to linux because linux is case sensitive).

Steps to reproduce:
Create a directory/path containing capital letters and set as value to target variable, attempt to attack afterwards and the target file/list file will not be found.

**Comment by jm33-m0** [comment]
Thanks for reporting, it's `cmd_handler()` making everything lowercase, I have fixed it so upper case inputs can be supported
