### ISSUE TITLE
Zoomeye Script Problem - exception handling

### ISSUE THREAD

**Issue by Vumasi** [jm33-m0/massExpConsole#7]
Hi, there is a problem with the zoomeye script it returns an error like "[-] Error with api_test", I try with the original script by evilclay and other script this works perfectly with my credentials.

Like using cURL it returns the access token.

I also search in the script I do not see where this little problem can come from.

In any case very good job that you carried out!

**Comment by jm33-m0** [comment]
thanks for your support! im not with my computer right now, what does the traceback info say?

**Comment by jm33-m0** [comment]
i just tested zoomeye script and it worked fine, screenshot attached:
![mec_zoomeye](https://cloud.githubusercontent.com/assets/10167884/26664233/8c2039dc-46c2-11e7-8faf-cc04c7b2638d.jpg)

**Comment by jm33-m0** [comment]
please make sure `zoomeye.conf` looks like this:
```
user:YourEmailAddr@example.com
password:ThisIsYourPassword
```
do not include any white spaces otherwise it might not work

**Comment by jm33-m0** [comment]
it does raise an exception **when the crawling is done**, but i am not sure what exactly causes this issue

![mec_zoomeye_bug](https://cloud.githubusercontent.com/assets/10167884/26665879/1bc24b6e-46cf-11e7-8169-1595e57c1e14.jpg)

**Comment by jm33-m0** [comment]
problem located:
`debug_traceback()` method throw a `NoneType: None` when there's no exception to print

**Comment by jm33-m0** [comment]
fixed
[fix zoomeye crawler and improve exception handling](https://github.com/jm33-m0/massExpConsole/commit/81ed48e7c0e22974ce38c880ca81eefa797b929c)

**Comment by Vumasi** [comment]
```
AttributeError: 'NoneType' object has no attribute '__context__'
Traceback (most recent call last):
  File "mec.py", line 449, in <module>
    main()
  File "mec.py", line 430, in main
    execute(cmd)
  File "mec.py", line 192, in execute
    debug_except()
  File "/root/new/massExpConsole/util/console.py", line 118, in debug_except
    tcbk = traceback.format_exc()
  File "/usr/lib/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
```
Return this now after you edit :)

**Comment by jm33-m0** [comment]
run `zoomeye.py` directly see what happens

**Comment by jm33-m0** [comment]
I've tested my script before pushing it to github, didn't see anything wrong with it

**Comment by jm33-m0** [comment]
tested again, it worked fine
![screenshot from 2017-06-03 11-06-10](https://cloud.githubusercontent.com/assets/10167884/26750085/9fe42fc4-484c-11e7-8727-b71b55e79505.png)

**Comment by Vumasi** [comment]
Not work this is returned :
```
Traceback (most recent call last):
  File "zoomeye.py", line 179, in <module>
    debug_traceback()
  File "/root/new/massExpConsole/util/console.py", line 118, in debug_except
    tcbk = traceback.format_exc()
  File "/usr/lib/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'

```

**Comment by jm33-m0** [comment]
@Vumasi try upgrading your python version to 3.5+

**Comment by Vumasi** [comment]
I try use Python 3.5 :
```
[*] Your query is: port:22
[*] How many results do you want? (10 IPs on each page) 4
[*] Crawling fetched pages from ZoomEye...


[+] Found 0 hostsyack? [y/n] 
NoneType

```

**Comment by jm33-m0** [comment]
i dont understand why you only want 4 results as one page contains 10 results at least, and one request can get you 10k results if you want

**please look into `zoomeye.py` and try modifying it if you believe my setting is unacceptable**

![screenshot from 2017-06-03 20-15-20](https://cloud.githubusercontent.com/assets/10167884/26753464/73bf611e-4899-11e7-8489-53bbc10e2849.png)

**Comment by Vumasi** [comment]
It's work i try with a lot of result ! Thanks :)
